//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_KATEGORILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_KATEGORILER()
        {
            this.Tbl_URUNLER = new HashSet<Tbl_URUNLER>();
        }
    
        public short KATEGORIID { get; set; }

        [Required(ErrorMessage ="Kategori Adý Boþ Geçilemez!!")] // kategori adýný veritabanýna boþ eklemicek boþ geçilemez artýk
        public string KATEGORIAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_URUNLER> Tbl_URUNLER { get; set; }
    }
}
