//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_MUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MUSTERILER()
        {
            this.Tbl_SATISLAR = new HashSet<Tbl_SATISLAR>();
        }
    
        public int MUSTERIID { get; set; }

        //VALÝDATÝON
        [Required(ErrorMessage ="Bu alaný Boþ Býrakamazsýnýz...")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakterlik isim giriniz")]
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SATISLAR> Tbl_SATISLAR { get; set; }
    }
}
